version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: codecritic_postgres
    environment:
      POSTGRES_DB: codecritic_db
      POSTGRES_USER: codecritic
      POSTGRES_PASSWORD: codecritic123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: codecritic_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: