"""Governed agent — auto-generated by Zumie Agent Discovery.

Credentials are embedded from registration.
Set ZUMIE_CLIENT_SECRET in your environment — never commit it.
"""
import os
from langman import Langman, LangmanDecisionDenied
import logging

logger = logging.getLogger(__name__)

langman = Langman.from_config(
    config_path="zumie-governance.yaml",
    agent_id="agent_002490e07400",
    client_id="client_8c434c8c199b",
    client_secret=os.environ["ZUMIE_CLIENT_SECRET"],
)


def call_tool(tool_name: str, payload: dict) -> dict:
    try:
        return langman.guard_execution(
            action_type="tool",
            action_name=tool_name,
            payload=payload,
            callback=lambda: _execute_tool(tool_name, payload),
        )
    except LangmanDecisionDenied as exc:
        logger.warning("Tool call denied: %s", tool_name)
        return {"error": f"Action denied by policy: {exc}"}


def call_model(model_name: str, prompt: str) -> str:
    try:
        return langman.guard_execution(
            action_type="model",
            action_name=model_name,
            payload={"prompt": prompt},
            callback=lambda: _execute_model(model_name, prompt),
        )
    except LangmanDecisionDenied as exc:
        logger.warning("Model call denied: %s", model_name)
        return f"Model call denied by policy: {exc}"


def _execute_tool(tool_name: str, payload: dict) -> dict:
    raise NotImplementedError(f"Implement tool: {tool_name}")


def _execute_model(model_name: str, prompt: str) -> str:
    raise NotImplementedError(f"Implement model client: {model_name}")


def main():
    print(call_model("gpt-4", "Run TestConfig"))


if __name__ == "__main__":
    main()
